<?php
defined('BASEPATH') OR exit('No direct script access allowed'); 
$route['events'] = 'events'; 
$route['sermons'] = 'sermons';
$route['church-building'] = 'main/buildingproject';
$route['contact'] = 'main/contact';
$route['gallery'] = 'main/gallery'; 
$route['ministries'] = 'ministries';
$route['news'] = 'news'; 
$route['auth'] = 'auth';
$route['auth/logout'] = 'auth/logout';
$route['auth/login'] = 'auth/login';
$route['auth/register'] = 'auth/register';
$route['dashboard'] = 'dashboard';
$route['events-list'] = 'dashboard/events_list';
$route['event-add'] = 'dashboard/event_add';
$route['news-list'] = 'dashboard/news_list';
$route['news-add'] = 'dashboard/news_add';
$route['gallery-list'] = 'dashboard/gallery_list';
$route['gallery-item-add'] = 'dashboard/gallery_item_add';
$route['sermons-list'] = 'dashboard/sermons_list';
$route['sermon-add'] = 'dashboard/sermon_add';
$route['default_controller'] = 'main';
$route['404_override'] = '';
$route['translate_uri_dashes'] = FALSE;